import React from 'react';
import { Shield, Sparkles, Swords, Zap, Compass } from 'lucide-react';

interface WelcomeScreenProps {
  onSignIn: () => Promise<void>;
  isLoading: boolean;
}

const WelcomeScreen: React.FC<WelcomeScreenProps> = ({ onSignIn, isLoading }) => {
  return (
    <div id="zanshin-welcome-screen" className="flex flex-col items-center justify-center text-center space-y-8 py-10">
      {/* Visual Shield Logo Element */}
      <div className="relative">
        <div className="absolute inset-0 bg-red-600/20 rounded-full blur-2xl animate-pulse"></div>
        <div className="w-24 h-24 rounded-full bg-gradient-to-b from-red-900/40 to-black border border-red-500/30 flex items-center justify-center relative z-10 shadow-[0_0_25px_rgba(239,68,68,0.2)]">
          <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M24 6V42" stroke="#EF4444" strokeWidth="4" strokeLinecap="round" />
            <path d="M12 24H36" stroke="white" strokeWidth="2.5" strokeLinecap="round" />
            <circle cx="24" cy="24" r="8" fill="#EF4444" className="animate-pulse" />
          </svg>
        </div>
      </div>

      {/* Main Title & Subtitle */}
      <div className="space-y-3">
        <h2 className="text-3xl font-black tracking-widest text-white">
          ZANSHIN <span className="text-red-500">残心</span>
        </h2>
        <p className="text-sm text-gray-400 max-w-xs mx-auto leading-relaxed">
          The state of continuous awareness. Elevate your Kendo practice with personalized training splits.
        </p>
      </div>

      {/* Key Features Bento Grid / Display Card */}
      <div className="glass rounded-2xl p-5 border border-white/5 w-full max-w-sm text-left space-y-4">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-red-950/30 rounded-lg text-red-500 mt-0.5 border border-red-900/30">
            <Swords size={16} />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-white">Bespoke Kendo Training</h4>
            <p className="text-xs text-gray-400">Gym, Home, and Dojo programs generated by expert AI Sensei.</p>
          </div>
        </div>

        <div className="flex items-start gap-3">
          <div className="p-2 bg-yellow-950/30 rounded-lg text-yellow-500 mt-0.5 border border-yellow-900/30">
            <Zap size={16} />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-white">Gamified Progression</h4>
            <p className="text-xs text-gray-400">Earn discipline XP, achieve ranks, and track your daily streaks.</p>
          </div>
        </div>

        <div className="flex items-start gap-3">
          <div className="p-2 bg-blue-950/30 rounded-lg text-blue-500 mt-0.5 border border-blue-900/30">
            <Compass size={16} />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-white">Durable Cloud Sync</h4>
            <p className="text-xs text-gray-400">Securely back up your metrics, history, and schedules with Firestore.</p>
          </div>
        </div>
      </div>

      {/* Auth Interaction Section */}
      <div className="w-full max-w-sm space-y-3 pt-4">
        <button
          onClick={onSignIn}
          disabled={isLoading}
          className="w-full bg-gradient-to-r from-red-600 to-rose-500 hover:from-red-500 hover:to-rose-400 text-white font-bold py-4 px-6 rounded-2xl transition-all shadow-[0_4px_20px_rgba(239,68,68,0.3)] hover:shadow-[0_4px_25px_rgba(239,68,68,0.45)] flex items-center justify-center gap-3 active:scale-[0.98] cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
        >
          {isLoading ? (
            <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
          ) : (
            <>
              {/* Custom Google Logo Icon */}
              <svg className="w-5 h-5 fill-current" viewBox="0 0 24 24">
                <path d="M12.24 10.285V13.4h6.887c-.275 1.565-1.88 4.604-6.887 4.604-4.33 0-7.859-3.578-7.859-8s3.529-8 7.859-8c2.46 0 4.105 1.025 5.047 1.926l2.427-2.334C17.955 2.192 15.34 1 12.24 1 6.033 1 1 6.033 1 12.24s5.033 11.24 11.24 11.24c6.478 0 10.793-4.537 10.793-10.986 0-.743-.08-1.3-.176-1.853H12.24z"/>
              </svg>
              <span>Sign In with Google</span>
            </>
          )}
        </button>
        <p className="text-[10px] text-gray-500 tracking-wider uppercase">
          Requires verification via secure Google Authentication
        </p>
      </div>
    </div>
  );
};

export default WelcomeScreen;
